"""initial schema

Revision ID: 298d6976a40e
Revises: 
Create Date: 2026-06-25 22:59:24.592403+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.models.base  # provides the TZDateTime custom type used below

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('suppressions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppressions_email'), ['email'], unique=True)

    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('subject_default', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('contact_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('contact_count', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verification_summary', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('import_summary', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('free_provider_filter_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('from_name', sa.String(length=200), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ip_pool', sa.String(length=100), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('queued_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('bounced_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['contact_lists.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verification_result', sa.String(length=20), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['contact_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_contacts_list_id'), ['list_id'], unique=False)
        batch_op.create_index('ix_contacts_list_status', ['list_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_status'), ['status'], unique=False)

    op.create_table('campaign_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('email_snapshot', sa.String(length=320), nullable=False),
    sa.Column('merge_snapshot', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('postal_message_id', sa.String(length=255), nullable=True),
    sa.Column('ip_pool', sa.String(length=100), nullable=True),
    sa.Column('last_event_at', app.models.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id', name='uq_recipient_campaign_contact')
    )
    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_recipients_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_recipients_postal_message_id'), ['postal_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_recipients_status'), ['status'], unique=False)
        batch_op.create_index('ix_recipient_campaign_status', ['campaign_id', 'status'], unique=False)

    op.create_table('email_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_recipient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('occurred_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_recipient_id'], ['campaign_recipients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_events_campaign_recipient_id'), ['campaign_recipient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_events_campaign_recipient_id'))

    op.drop_table('email_events')
    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.drop_index('ix_recipient_campaign_status')
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_postal_message_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_campaign_id'))

    op.drop_table('campaign_recipients')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_status'))
        batch_op.drop_index('ix_contacts_list_status')
        batch_op.drop_index(batch_op.f('ix_contacts_list_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))

    op.drop_table('contacts')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))

    op.drop_table('campaigns')
    op.drop_table('contact_lists')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('templates')
    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppressions_email'))

    op.drop_table('suppressions')
    op.drop_table('app_settings')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
