"""planner

Revision ID: ea2eda13f5bf
Revises: 0002_reply_to
Create Date: 2026-06-27 15:29:26.742470+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base  # provides the TZDateTime custom type used below


# revision identifiers, used by Alembic.
revision: str = '0003_planner'
down_revision: Union[str, None] = '0002_reply_to'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_warm_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('pool', sa.String(length=100), nullable=True),
    sa.Column('warmed_since', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('campaign_contact_sends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id', name='uq_contact_send')
    )
    with op.batch_alter_table('campaign_contact_sends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_contact_sends_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_contact_sends_contact_id'), ['contact_id'], unique=False)

    op.create_table('campaign_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['contact_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'list_id', name='uq_campaign_list')
    )
    with op.batch_alter_table('campaign_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_lists_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_lists_list_id'), ['list_id'], unique=False)

    # Data migration: copy each campaign's existing single list_id into the new
    # many-to-many join (the new source of truth for a campaign's lists).
    op.execute(
        "INSERT INTO campaign_lists (campaign_id, list_id, created_at) "
        "SELECT id, list_id, CURRENT_TIMESTAMP FROM campaigns WHERE list_id IS NOT NULL"
    )

    op.create_table('planner_placements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'week', 'weekday', name='uq_placement_cell')
    )
    with op.batch_alter_table('planner_placements', schema=None) as batch_op:
        batch_op.create_index('ix_placement_cell', ['week', 'weekday'], unique=False)
        batch_op.create_index(batch_op.f('ix_planner_placements_campaign_id'), ['campaign_id'], unique=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_time', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('send_timezone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_planner', sa.Boolean(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('parent_campaign_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_campaigns_is_planner'), ['is_planner'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_parent_campaign_id'), ['parent_campaign_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_campaigns_parent_campaign', 'campaigns',
            ['parent_campaign_id'], ['id'], ondelete='SET NULL',
        )

    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_email_events_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_events_status'))
        batch_op.drop_column('status')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint('fk_campaigns_parent_campaign', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_campaigns_parent_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_is_planner'))
        batch_op.drop_column('parent_campaign_id')
        batch_op.drop_column('is_planner')
        batch_op.drop_column('send_timezone')
        batch_op.drop_column('send_time')

    with op.batch_alter_table('planner_placements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planner_placements_campaign_id'))
        batch_op.drop_index('ix_placement_cell')

    op.drop_table('planner_placements')
    with op.batch_alter_table('campaign_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_lists_list_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_lists_campaign_id'))

    op.drop_table('campaign_lists')
    with op.batch_alter_table('campaign_contact_sends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_contact_sends_contact_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_contact_sends_campaign_id'))

    op.drop_table('campaign_contact_sends')
    op.drop_table('ip_warm_states')
    # ### end Alembic commands ###
